image: gcc

update:
  stage: .pre
  script:
    - apt-get update

build:
  stage: build
  before_script:
    - apt-get -y install cmake make valgrind gcc doxygen
  script:
    - mkdir build; cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc
    - make -j
    - cd ..
  artifacts:
    paths:
      - build/
      - bin/
      - lib/

test:
  stage: test
  before_script:
    - apt-get -y install python3 python3-pip
    - pip3 install gcovr
  script:
    - cd build
    - ctest --output-on-failure -T MemCheck
    - gcovr . --root .. --exclude ../test/ --exclude-unreachable-branches --print-summary --xml=coverage.xml --xml-pretty --html=coverage.html
    - cd ..
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    paths:
      - build/
    reports:
      cobertura: build/coverage.xml

pages:
  stage: deploy
  rules:
    - if: "$CI_COMMIT_TAG"
  script:
    - cd build
    - make docs
    - cd ..
    - cp build/html/ public/
    - cp build/coverage.html public/coverage.html
  artifacts:
    paths:
      - public/
