image: gcc

build_and_test:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install cmake make valgrind
  script:
    - mkdir build; cd build
    - cmake ..
    - make -j
    - ctest --output-on-failure -T MemCheck
    - cd ..
    - |
      TIMESTAMP=$(cat build/Testing/TAG -n 1)
      cp build/Testing/$TIMESTAMP/*.xml build/Testing/
  artifacts:
    paths:
      - build/
      - bin/
      - lib/
      - build/Testing/*.xml
