image: gcc

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

build-and-test:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install cmake make valgrind doxygen
  script:
    - mkdir build; cd build
    - cmake ..
    - make -j
    - ctest --output-on-failure -T MemCheck
    - if [ -n "$CI_COMMIT_TAG" ]; then make docs; fi
    - cd ..
  artifacts:
    paths:
      - build/
      - bin/
      - lib/
